### ISSUE TITLE
Implement the first draft of the library

### ISSUE THREAD

**Issue by ZER0** [dusk-network/exu#1]
# Epic

## Summary

This library is essential due to the current performance issues in the [Web Wallet].
Currently, we load the [wallet-core], a WebAssembly Module, on the main thread. This practice hinders normal UI operations, resulting in a subpar user experience.

Furthermore, direct loading of the WASM module on the main thread prevents concurrent code execution, the ability to terminate long-running calls, and code isolation.

The purpose of this library is to address all of these challenges and more. It offers initial APIs that streamline WebAssembly calls in a generic manner, allowing for easy integration as the first step in [dusk-wallet-js] without requiring any modifications to the [Web Wallet] code.

See also: dusk-network/web-wallet#907.

## Tasks

- [x] dusk-network/web-wallet#2
- [x] Implement the library core code
- [x] Add unit testing
- [x] Add documentation, CHANGELOG and README

[Web Wallet]: https://github.com/dusk-network/web-wallet
[wallet-core]: https://github.com/dusk-network/wallet-core
[dusk-wallet-js]: https://github.com/dusk-network/dusk-wallet-js
